spring.application.name=financeiro
spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=rm555573
spring.datasource.password=090805
spring.jpa.hibernate.ddl-auto=update
springdoc.packages-to-scan=br.com.restaurante.financeiro
